name: apto
description: Darsh Chaudhary - Computer Science IA

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  google_fonts: ^6.2.0
  email_validator: '^2.1.16'
  firebase_core: ^2.24.2
  firebase_auth: ^4.16.0
  cloud_firestore: ^4.14.0
  modal_progress_hud_nsn: ^0.5.1
  flutter_downloader: ^1.11.7
  path_provider: ^2.1.3
  permission_handler: ^11.0.1
  dio: ^5.4.3+1
  email_otp: ^2.1.2
  email_auth: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg


  fonts:
    - family: SansitaOne
      fonts:
        - asset: fonts/SansitaOne.ttf
